### ISSUE TITLE
Causing an 502 Error on Return to setup.

### ISSUE THREAD

**Issue by Deadlander** [baileymh/pf1e-content#19]
When using pf1e-content with any other PF1e mod, including pf1e-archetypes, this mod is causing an 502 error upon using Return to Setup.  

I have been able to verify this through repeated switching of mods and the only common denominator is pf1e-content.

**Comment by baileymh** [comment]
I'm not able to recreate this. When I Return to Setup, it works fine. Are you hosting locally? or from a server? If its a server, how much RAM is there?

**Comment by Deadlander** [comment]
I host through MoltenHosting.com.  I sent a message to the guy running it to find out how much RAM it has.  I am currently downloading my game information and mods to see if I can recreate it locally.  I hadn't thought of that before.  I will update once I have tested it.  Should be within the hour.

**Comment by Deadlander** [comment]
So, I downloaded the world and mods and it all worked fine on my local machine.  The guy who runs MoltenHosting says each server gets 2GB.

**Comment by baileymh** [comment]
I think it's an issue related to the server. You might try troubleshooting the 502 error with your browser: clearing the cache, check your firewall, and DNS settings.

This module adds a lot of content and requires a moderate load on RAM, above and beyond what the pf1 system requires, which is substantial. It's possible a combination of your browser settings / cache and the amount of stuff needed to unload from RAM is resulting in an error.

Either way, I don't think there is anything I can do to help you with this. Hope you're able to get it resolved on your end though.

**Comment by Deadlander** [comment]
Thanks!  Once he told me two Gb of RAM per server, I figured that is what is causing it.
