### ISSUE TITLE
Warning loading in Foundry >=9.249

### ISSUE THREAD

**Issue by allardhoeve** [baileymh/pf1e-content#37]
Hey! Thank you for making this available! I subscribed to your Parteon.

I get this warning in the Foundry logs when I install the package:

```
Feb 05 15:52:39 ubuntu-s-1vcpu-1gb-ams3-01 node[2398]: FoundryVTT | 2022-02-05 15:52:39 | [warn] Package pf-content contains 36 compendium definitions that still use the deprecated 'entity' field instead of 'type'.
Feb 05 15:52:39 ubuntu-s-1vcpu-1gb-ams3-01 node[2398]: FoundryVTT | 2022-02-05 15:52:39 | [warn] Package pf-content is using the old "systems" manifest key where a "system" key is expected
Feb 05 15:52:39 ubuntu-s-1vcpu-1gb-ams3-01 node[2398]: FoundryVTT | 2022-02-05 15:52:39 | [warn] Package pf1e-archetypes contains 4 compendium definitions that still use the deprecated 'entity' field instead of 'type'. 
```

Thanks

**Comment by baileymh** [comment]
Gotcha. I haven't updated to there yet, so what you can do in the mean time is try to manually force a migration, that should take care of it. If not, let me know. 

Also, thank you for the Patreon sub. It's really appreciated!

**Comment by baileymh** [comment]
The update should have taken care of this. If there is still an issue, let me know.
