### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by chlorophant** [baileymh/pf1e-content#53]
@baileymh 

I'm looking at making my own DM tool, and was curious what the source was for the data you guys have?

I've been writing a scraping tool for aonprd, but it looks like you guys have a lot of the work done already. If the source is aonprd, then it might save me some time to use what you have already.

Please let me know, it could save me countless hours.

Thank you!

**Comment by baileymh** [comment]
Hey @chlorophant 
Yea, I basically scrapped aonprd for a fair amount of it, and then put everything into tables. I also had access through a friend to the backend src tables for data for a lot of sections, mostly items, gear, mobs, etc. 

I'm happy to share what I have, though I'll admit my programming skills are basic, so the data isn't as clean as if someone wrote a python or js to do it specifically. 

Are there things in particular that you were wanting?

**Comment by chlorophant** [comment]
Well I really want the data to be as clean as possible. Perhaps you could send me the data that came directly from the aonprd backend? Doubt it gets much cleaner than that!

Would you mind adding me on discord? 

Username: Chloro#1638

**Comment by chlorophant** [comment]
@baileymh
