### ISSUE TITLE
Missing Traits

### ISSUE THREAD

**Issue by xeth1313** [baileymh/pf1e-content#6]
The trait Community-Minded, https://aonprd.com/TraitDisplay.aspx?ItemName=Community-Minded , is missing.
The trait Fool for Friends, https://aonprd.com/TraitDisplay.aspx?ItemName=Fools%20for%20Friends , is missing.
The trait Ancestral Weapon (Numeria), https://aonprd.com/TraitDisplay.aspx?ItemName=Ancestral%20Weapon , is missing
The trait Dilettante Artist, https://aonprd.com/TraitDisplay.aspx?ItemName=Dilettante%20Artist , is missing/

**Comment by Amd321** [comment]
Thanks for the notice. The traits section isn't complete yet, and some are missing. Sections that are still being finished are race and regional traits, as well as any 3.5 material which is being put into a separate compendium. The above have already been marked down for addition.
