### ISSUE TITLE
Missing source and related content

### ISSUE THREAD

**Issue by xeth1313** [baileymh/pf1e-content#9]
One of the last Pathfinder books made by Paizo is the Niobe sourcebook. It includes a new race, new class, some archetypes, feats, and magic items. The race and class have already very included in the base Pathfinder foundry content https://cse.google.com/cse?cx=006680642033474972217%3A6zo0hx_wle8&q=Niobe#gsc.tab=0&gsc.q=Niobe&gsc.page=1

**Comment by Amd321** [comment]
As far as I know that material is 3pp made by Stranger comics. It's the goal of this module to only add official sources located on https://www.aonprd.com/. Last time I checked Foundry pf1e wasn't adding 3pp, unless that slipped through the cracks.

**Comment by xeth1313** [comment]
The book was made by Paizo. It is like the Vampire Hunter D book, in that
it is made by Piazo but not set in Golarion. Both were Kickstarter
releases, and not sold directly by Paizo. Both of those books are missing
from Archives of Nethtys because they only host the Golarian content. Here
is the blog post about it :
https://paizo.com/community/blog/v5748dyo6sgbs?World-of-Niobe
And  all of the content on pfsrd lists Piazo in the copyright section, it
is just sold and distributed by Stranger Things Comics:
"Pathfinder Roleplaying Game: Niobe © 2019, Paizo Inc.; Authors: Sebastian
A. Jones, Darrell May, Joshua Cozine, and Luis Loza."

**Comment by King-Kronos** [comment]
It's technically 3pp being made my stranger comics.
